### ISSUE TITLE
Use of base_scan vs base_scan_raw

### ISSUE THREAD

**Issue by ruffsl** [googlecartographer/cartographer_fetch#3]
I'd like to ask about the pros and cons of filtering laser data for cartographer. By default the fetch provides two scan topics, [`base_scan_raw`](https://github.com/fetchrobotics/fetch_robots/blob/23c54a66f42e05cf6d775e595d9e4d248d9f9bfa/freight_bringup/launch/include/laser.launch.xml#L10) and [`base_scan`](https://github.com/fetchrobotics/fetch_robots/blob/23c54a66f42e05cf6d775e595d9e4d248d9f9bfa/freight_bringup/launch/include/laser.launch.xml#L15). The scan topic `base_scan_raw` comes straight from the ros node for the SICK network driver, and the `base_scan` is a filtered version of `base_scan_raw` to remove the LIDAR's [shadow artifacts](http://wiki.ros.org/laser_filters/Tutorials/Laser%20filtering%20using%20the%20filter%20nodes#Filtering_a_Scan:_The_Scan_Shadows_Filter). In this package, it looks like raw is used, and so I'd like to ask if one is better that the other, or in what cases. As most of our environments at floor level have many spindly furniture fittings and generate a lot of shadows, and am wondering if some cartographer perams may be sensitive to those.

I've collected a figure 8 trajectory bagfile on our floor, and maps using raw and filtered scan topics for comparison, [drive link](https://drive.google.com/drive/folders/0B-NnnBv9ICndMDM0dHdxVmhleEE?usp=sharing
). It looks like the raw catches more edges/wall voxels, but filtered sustains a cleaner dilated free space in small cluttered areas.

### Raw:
![image](https://cloud.githubusercontent.com/assets/2293573/22607142/6b9c2a2c-ea0b-11e6-974c-0c6314949362.png)

### Filtered:
![image](https://cloud.githubusercontent.com/assets/2293573/22607214/aae7798e-ea0b-11e6-804a-21885f45036d.png)

As an aside, perhaps I should increase the `LaserFanInserterOptions.miss_probability` to fix the missing free space? The freight's velocity was a brisk striding pace, and perhaps faster than originally configured. Also should one increase `cartographer.mapping_2d.proto.SubmapsOptions.resolution`  or decrease `cartographer.mapping_2d.proto.SubmapsOptions.half_length` to acquire more pixels/meter from the map servier topic?

**Comment by SirVer** [comment]
@damonkohler has most experience. Afaik we do not have a non-simulated fetch yet though, so our knowledge might be limited here.

**Comment by damonkohler** [comment]
I configured it to use the raw scan simply because that's what we've always done. There's nothing inherently wrong with using the filtered scan instead. Personally, I don't see an appreciable difference in the maps you shared.

The missing free space looks like the result we'd expect to see from map_saver/map_server. It stems from the implementation of thresholding to replace the gradient with a ternary map. Instead of changing the miss/hit probabilities, which can affect mapping quality, it's better to change the thresholds to allow a higher "uncertainty".

I believe our /finish_trajectory service saves the map as gray scale instead of ternary. You may have to change/configure map_server to make better use of the full range of values.
